### ISSUE TITLE
dump as JSON?

### ISSUE THREAD

**Issue by dcsan** [lazerwalker/twison#10]
it seems this relies on client side javascript to run

is there a way to get the JSON output from a server side script?
or even a way to access the raw twine internal XML just as a pure data dump?

ideally so I could do something like `curl $storyUrl > file.json`

I want to use the twine editor/authoring tool, but building my own runtime. 
currently a server cant really talk to this export tool, it has to be done manually in the Twine UI to "export as JSON..."

**Comment by lazerwalker** [comment]
The reliance on client-side javascript comes from Twine 2 itself; the only official hooks for custom story formats in Twine 2 are all based on client-side JavaScript.

More importantly, Twine 2 stories are only stored locally in LocalStorage, not online. Building a tool that does e.g. `curl $storyUrl > file.json` could only work on the computer that created the story, since they're not stored on Twine's servers and URLs only work locally.

Without having the time to dive deeply into what you're actually trying to do, I'd recommend looking into one of the two following options:

* Use Twine 1 instead of Twine 2

* Write your own story format (perhaps using Twison as a jumping-off point) that, as part of the "export to JSON" process, automatically uploads the JSON to your server.

**Comment by dcsan** [comment]
yeah, i came to the conclusion it would be easier to write my own authoring UI than try to bend the existing twine to my needs.

to that end did you come across any other tools that have similar functionality to twine?

we had some discussion here too:
https://github.com/aichaos/rivescript-js/issues/22

**Comment by lazerwalker** [comment]
I'm actually in the process of building out my own general-purpose storytelling engine and Twine-like authoring tool suite as part of my research at MIT.

The engine's going to be open-sourced fairly soon, but it'll be quite some time before it or the authoring tools are even remotely production-ready.

**Comment by dcsan** [comment]
does it coincide with any of the objectives outlined in that thread on rivescript?
its a fairly topical area. I'd be interested to compare design notes with you. we have a need for such tools for our english language learning adventure game, but have really just been building the minimum to develop the content.

http://ComicEnglish.com
story ->
http://comicenglish.com/lessons/leak/start/start

chatbots and messaging is such a hot topic this year, but the authoring tools are all mostly for very simple dialogs, like slot filling for an IoT controller.
