### ISSUE TITLE
Links no longer being split in name and link correctly

### ISSUE THREAD

**Issue by glaap** [lazerwalker/twison#12]
I'm on OS X El Capitan.
No matter which version of Twine or default browser I use, I always get this output:

   "links": [
        {
          "name": "I wanted to ask you the same.|Intro1-2",
          "link": "I wanted to ask you the same.|Intro1-2"
        },
        {
          "name": "Hello? Who is this?|Intro1-1",
          "link": "Hello? Who is this?|Intro1-1"
        }

**Comment by lazerwalker** [comment]
Twison links follow the same structure as Twine 2 Harlowe links, which means they should look like `[[text->destinationNode]]` rather than `[[text|destinationNode]]`. 

A passage that contains the text `[[I wanted to ask you the same.|Intro1-2]]` should in fact generate that JSON you've pasted. I assume that's what's going on here?
