### ISSUE TITLE
https http

### ISSUE THREAD

**Issue by zaccolley** [lazerwalker/twison#15]
Hey, if you use glitch.com or surge you can get https for free

**Comment by lazerwalker** [comment]
Hey, thanks so much for writing in!

I assume you're talking about the complications regarding the story format JS file being served over HTTP instead of HTTPS?

Right now, that JS is hosted on my personal site (lazerwalker.com). It's hosted on GitHub Pages, since it's just static content, but sadly GitHub pages doesn't yet support HTTPS for custom domains. I'd love to switch over to HTTPS soon, but given that it's just a bunch of static HTML/CSS/JS files, I'd like to avoid hosting like Glitch or Surge that add complexity I don't need. Switching over to GitLab's static file hosting is on my to-do list.

Let me know if that's not what you're talking about! Will leave this open as a motivator to get me to actually do this :)

Thanks again!

**Comment by zaccolley** [comment]
sorry gave very little context ahah,

sounds good!

**Comment by lazerwalker** [comment]
My personal site is now serving up HTTPS content, so this is fixed! Link updated in the README.
